version: '3'

services:
  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
      - node_modules-admin:/var/www/node_modules
    networks:
      umihiko-server_default:
    stdin_open: true
    tty: true
    command: yarn start
    ports:
      - 3001:3000

volumes:
  node_modules-admin:

networks:
  umihiko-server_default:
    external: true
