version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx/log:/var/log/nginx/
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - admin

  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
      - node_modules-admin:/var/www/node_modules
    stdin_open: true
    tty: true
    command: yarn start

volumes:
  node_modules-admin:
